version: '3.5'
services:
 postgres-server:
   container_name: zabbix-pgsql
   image: postgres:14-alpine
   #  command: -c ssl=on -c ssl_cert_file=/run/secrets/server-cert.pem -c ssl_key_file=/run/secrets/server-key.pem -c ssl_ca_file=/run/secrets/root-ca.pem
   volumes:
     - ./volumes/zabbix-pgsql/var/lib/postgresql/data:/var/lib/postgresql/data:rw
     #- ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
     #- ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
     #- ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
   env_file:
     - ./env_vars/.env_db_pgsql
   secrets:
     - POSTGRES_USER
     - POSTGRES_PASSWORD
   #environment:
     #- POSTGRES_USER=zabbix
     #- POSTGRES_PASSWORD=zabbix_pwd
     #- POSTGRES_DB=zabbix
   networks:
    zbx-net:
     aliases:
      - postgres-server
      - pgsql-server
      - pgsql-database

 zabbix-snmptraps:
  container_name: zabbix-snmptraps
  image: zabbix/zabbix-snmptraps:alpine-6.4-latest
  ports:
   - "162:1162/udp"
  volumes:
   - snmptraps:/var/lib/zabbix/snmptraps:rw
  networks:
   zbx-net:
    aliases:
     - zabbix-snmptraps
  labels:
   com.zabbix.description: "Zabbix snmptraps"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "snmptraps"
   com.zabbix.os: "alpine"

 zabbix-server:
   container_name: zabbix-server
   image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
   ports:
    - "10051:10051"
   volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro 
    - ./volumes/zabbix-server/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
    - ./volumes/zabbix-server/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
    - ./volumes/zabbix-server/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
    - ./volumes/zabbix-server/var/lib/zabbix/export:/var/lib/zabbix/export:rw
    - ./volumes/zabbix-server/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
    - ./volumes/zabbix-server/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
    - ./volumes/zabbix-server/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    - ./volumes/zabbix-server/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
    - ./volumes/zabbix-server/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
    #   - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
    #   - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
    #   - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
   env_file:
    - ./env_vars/.env_db_pgsql
    - ./env_vars/.env_srv
   secrets:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
   #environment:
    #- POSTGRES_USER=zabbix
    #- POSTGRES_PASSWORD=zabbix_pwd
    #- POSTGRES_DB=zabbix
   depends_on:
    - postgres-server
   networks:
    zbx-net:
      aliases:
       - zabbix-server
       - zabbix-server-pgsql
       - zabbix-server-alpine-pgsql
       - zabbix-server-pgsql-alpine
   sysctls:
    - net.ipv4.ip_local_port_range=1024 65000
    - net.ipv4.conf.all.accept_redirects=0
    - net.ipv4.conf.all.secure_redirects=0
    - net.ipv4.conf.all.send_redirects=0
   labels:
    com.zabbix.description: "Zabbix server with PostgreSQL database support"
    com.zabbix.company: "Zabbix LLC"
    com.zabbix.component: "zabbix-server"
    com.zabbix.dbtype: "pgsql"
    com.zabbix.os: "alpine"

 zabbix-web-nginx-pgsql:
  container_name: zabbix-nginx
  image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
  ports:
   - "80:8080"
   - "443:8443"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./volumes/zabbix-nginx/etc/ssl/nginx:/etc/ssl/nginx:ro
   - ./volumes/zabbix-nginx/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
   #- ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
   #- ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
   #- ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
  env_file:
   - ./env_vars/.env_db_pgsql
   - ./env_vars/.env_web
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  #environment:
    #- ZBX_SERVER_HOST=zabbix-server
    #- DB_SERVER_HOST=postgres-server
    #- POSTGRES_USER=zabbix
    #- POSTGRES_PASSWORD=zabbix_pwd
    #- POSTGRES_DB=zabbix  
  depends_on:
   - postgres-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx-net:
    aliases:
     - zabbix-web-nginx-pgsql
     - zabbix-web-nginx-alpine-pgsql
     - zabbix-web-nginx-pgsql-alpine
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with PostgreSQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "alpine"

 zabbix-agent:
  container_name: zabbix-agent
  image: zabbix/zabbix-agent:alpine-6.4-latest
  ports:
   - "10050:10050"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./volumes/zabbix-agent/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ./volumes/zabbix-agent/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./volumes/zabbix-agent/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./volumes/zabbix-agent/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  env_file:
   - ./env_vars/.env_agent
  privileged: true
  pid: "host"
  networks:
   zbx-net:
    aliases:
     - zabbix-agent
     - zabbix-agent-passive
     - zabbix-agent-alpine 
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "alpine"

networks:
  zbx-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
volumes:
  snmptraps:

secrets:
  POSTGRES_USER:
    file: ./env_vars/.POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./env_vars/.POSTGRES_PASSWORD
